name: Run Python Script
on:
  schedule:
    - cron: '*/60 * * * *'  
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
 # This schedule will run the job every day at midnight UTC (adjust to your timezone)


  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Python script
      run: |
            python sstpTableWithSpeddtest.py 
            git config --global user.email "mehdi.hoore@gmail.com"
            git config --global user.name "mehdihoore"
            git add -A
            git commit -m "🚀 Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
            git push

