name: Python Script

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - run: 

        python sstpTableWithSpeddtest.py
    - uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main 
