name: Update SSTP Server List

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour at the start of the hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run Python script and commit changes
        run: |
          python sstpTableWithSpeddtest.py
          python chsangeHTML.py

          # Get the current Persian date and time
          persian_now=$(date '+%Y/%m/%d %H:%M:%S' | iconv -f ascii -t utf-8 | LC_CTYPE=en_US.utf-8 sed 's/\([Û°-Û¹]\)/\1/g')

          git config --global user.email "mehdi.hoore@gmail.com"
          git config --global user.name "mehdihoore"
          git add -A
          git commit -m "ðŸš€ Servers Updated - $persian_now"
          git push
