on:
  schedule:
      - cron: '0 */3 * * *' # Run every 3 hours at the start of the hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r requirement.txt

      - name: Run Python script and commit changes
        run: |
          python sstpTableWithSpeddtest.py
          python chsangeHTML.py
          python tebot.py
          git config --global user.email "mehdi.hoore@gmail.com"
          git config --global user.name "mehdihoore"
          git add -A
          git commit -m "🚀 Servers Updated - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
